# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Automate Agility - DevOps Coach, Engineer, Continuous Learner and Technology Explorer
email: eric.the.starr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AutomateAgility.com is dedicated to the learning and teaching of DevOps
  best practices, tooling and technology with the occassional venture into
  innovation areas not directly related to DevOps.  Learning is a never-ending
  journey and not a destination.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://automateagility.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ericjstarr
github_username:  starrman777

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: ['README.md','Gemfile','Gemfile.lock']
